version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: jaguit6/api-devops-up
    container_name: fastapi-app-up
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000