version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app-up
    ports:
      - "8000:8000"
    environment: #variables guardadas en archivo .env que no se versiona, cambiar nombre de .env.template a .env
      NEW_RELIC_CONFIG_FILE: newrelic.ini
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}

    command: ["newrelic-admin", "run-program", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]